#file name depends clusterGroupName in values-global.yaml
#
clusterGroup:
  name: hub
  isHubCluster: true

  scheduler:
    mastersSchedulable: true

  namespaces:
  - echo
  - curl:
      annotations:
        egressip-ipam-operator.redhat-cop.io/egressipam: default-egressipam
        egressip-ipam-operator.redhat-cop.io/egressips: 10.0.0.225
  - egressip-ipam-operator:
      operatorGroup: true
      targetNamespaces: null

  subscriptions:
    egressipam:
      name: egressip-ipam-operator
      channel: alpha
      source: community-operators
      sourceNamespace: openshift-marketplace
      csv: egressip-ipam-operator.v1.2.4

  nodes:
  - node03.ocp4.gmbros.local:
      labels:
        egressGateway: true

  applications:
    echo:
      name: echo
      namespace: echo
      project: default
      path: charts/echo
    curl:
      name: curl
      namespace: curl
      project: default
      path: charts/curl
    egressipam:
      name: egress-ipam-operator
      project: default
      path: charts/egress-ipam-operator

vars:
  curl:
    namespace: curl
    url: http://echo-echo.apps.ocp4.gmbros.local/say/hello
    sleep: 5
    timeout: 5
    node: node03.ocp4.gmbros.local
  egressipam:
    name: default-egressipam
    cidr: 10.0.0.0/24
    topologyLabel: egressGateway
